[lab_servers]
alma-node-01 ansible_host=192.168.10.x
alma-node-02 ansible_host=192.168.10.y
alma-node-03 ansible_host=192.168.10.z

[all:vars]
# Como ya habilitamos el usuario nexar con privilegios wheel:
ansible_user=tu_usuario
# Especificamos que use la llave SSH que creaste
ansible_ssh_private_key_file=~/.ssh/tu_llave_ssh
# Esto evita que Ansible falle si el fingerprint del server cambia
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
